/**
 * Shared UI surface area. Prefer importing directly from here instead of the
 * legacy '@/shared/components' barrel.
 */

export { Button, IconButton, PlainButton, RoundButton, UserButton } from './Button'
export { ActionButton } from './ActionButton'
export { Badge, type BadgeProps, type BadgeVariant, type BadgeSize } from './Badge'
export { Avatar, type AvatarProps, type AvatarSize, type AvatarShape } from './Avatar'
export { LoadingSpinner, LoadingOverlay, type LoadingSpinnerProps, type LoadingOverlayProps, type SpinnerSize, type SpinnerColor } from './LoadingSpinner'
export { EmptyState, type EmptyStateProps } from './EmptyState'
export { Alert, type AlertProps, type AlertVariant } from './Alert'
export { AddressFormGroup, type AddressFormGroupProps, type Address } from './AddressFormGroup'
export { IconBox, type IconBoxProps, type IconBoxSize, type IconBoxColor } from './IconBox'
export { AuthInput } from './AuthInput'
export { AuthLogo } from './AuthLogo'
export { WhiteLogo } from './WhiteLogo'
export { Card, ActionCard } from './Card'
export { Checkbox } from './Checkbox'
export { Toggle, type ToggleProps } from './Toggle'
export { Input } from './Input'
export { Textarea } from './Textarea'
export { RadioGroup } from './RadioGroup'
export { Modal } from './Modal'
export { SearchInput } from './SearchInput'
export { SectionHeader } from './SectionHeader'
export { ViewModeToggle } from './ViewModeToggle'
export type { ViewMode, ViewModeOption } from './ViewModeToggle'
export { Pagination } from './Pagination'
export { PasswordStrengthIndicator } from './PasswordStrengthIndicator'
export { Toast } from './Toast'
export { PhoneInput } from './PhoneInput'
export { PhoneDisplay } from './PhoneDisplay'
export type { PhoneDisplayProps, CountryInfo } from './PhoneDisplay'
export { FormInput } from './FormInput'
export { FileInput, type FileInputProps } from './FileInput'
export { NumberInput, type NumberInputProps } from './NumberInput'
export { DateInput, type DateInputProps } from './DateInput'
export { TimeInput, type TimeInputProps } from './TimeInput'
export { MaskedInput, type MaskedInputProps, type MaskType } from './MaskedInput'
export { Autocomplete, type AutocompleteProps, type AutocompleteSuggestion } from './Autocomplete'
export { ApiDropdown, countryDropdownConfig, currencyDropdownConfig, timezoneDropdownConfig, type ApiDropdownConfig, type ApiDropdownOption } from './ApiDropdown'
export { UiDropdown, type UiDropdownOption } from './UiDropdown'
export { dropdownStyles, getOptionClasses } from './dropdown-styles.config'
export { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, SortableTableHead } from './Table'
